module.exports = {
  env: {
    browser: true,
    es2021: true,
    es6: true,
    node: true,
  },
  settings: {
    react: {
      version: "detect",
    },
  },
  globals: {
    error: true,
    global: true,
    window: true,
    formatters: true,
    localStorage: true,
    location: true,
  },
  parser: "@typescript-eslint/parser",
  plugins: [
    "react",
    "react-hooks",
    "@typescript-eslint",
  ],
  extends: [
    "airbnb",
    "eslint:recommended",
  ],
  ignorePatterns: ["gists/*", "client-production/*"],
  rules: {
    radix: ["off"],
    "no-var": ["warn"],
    "max-len": ["off"],
    "no-console": ["off"], // error || WARN for final deployment check
    "func-names": ["off"],
    "no-plusplus": ["off"],
    "arrow-parens": ["off"],
    "prefer-const": ["off"],
    "no-unused-vars": ["off"], // error || WARN for final deployment check
    "arrow-body-style": ["off"],
    "import/extensions": ["off"],
    "no-param-reassign": ["off"],
    "no-nested-ternary": ["off"],
    "consistent-return": ["off"],
    "no-underscore-dangle": ["off"],
    "max-classes-per-file": ["off"],
    "no-use-before-define": ["off"],
    "no-restricted-syntax": ["off"],
    "object-curly-newline": ["off"],
    "prefer-destructuring": ["off"],
    "import/no-unresolved": ["off"],
    "no-restricted-globals": ["off"],
    "array-callback-return": ["off"],
    "no-constant-condition": ["off"],
    "object-property-newline": ["off"],
    "implicit-arrow-linebreak": ["off"],
    "no-unsafe-optional-chaining": ["off"],
    "import/prefer-default-export": ["off"],
    "import/no-extraneous-dependencies": ["off"],
    "react/function-component-definition": ["off"],
    "jsx-a11y/media-has-caption": ["off"],
    "jsx-a11y/label-has-associated-control": ["off"],
    "jsx-a11y/click-events-have-key-events": ["off"],
    "jsx-a11y/no-static-element-interactions": ["off"],
    "jsx-a11y/anchor-is-valid": ["off", {
      components: ["Link"],
      specialLink: ["to"],
    }],
    "react/jsx-no-constructed-context-values": ["off"],
    "react/jsx-one-expression-per-line": ["off"],
    "react/jsx-closing-tag-location": ["off"],
    "react/destructuring-assignment": ["off"],
    "react/jsx-no-useless-fragment": ["off"],
    "react/jsx-first-prop-new-line": ["off"],
    "react/jsx-props-no-spreading": ["off"],
    "react/jsx-filename-extension": ["off"],
    "react/no-unescaped-entities": ["off"],
    "react/require-default-props": ["off"],
    "react/no-array-index-key": ["off"],
    "object-curly-spacing": ["warn", "always"],
    "comma-dangle": ["warn", "always-multiline"],
    "no-multiple-empty-lines": ["warn", { max: 2 }],
    indent: ["error", 2, { SwitchCase: 1 }],
    "@typescript-eslint/no-explicit-any": ["off"],
    "eol-last": ["warn", "always"],
    quotes: ["warn", "double"],
    semi: ["warn", "always", { omitLastInOneLineBlock: true }],
    "linebreak-style": 0,
    "block-spacing": ["error"],
  },
};